theme = "slick"

icons = "awesome"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp2s0"
speed_up = false
speed_down = false
signal_strength = true

[[block]]
block = "net"
device = "wlo1"
ssid = false
speed_up = false
speed_down = false

[[block]]
block = "time"
interval = 60
format = "%R %a %d %b"

[[block]]
block = "custom"
command = "~/.scripts/layout.sh"
interval = 1
